name: Update NetGuard Hosts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # daily at 00:00 UTC

jobs:
  combine_hosts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl grep sed coreutils

      - name: Download and combine host files
        run: |
          FILES=(
            "https://raw.githubusercontent.com/REIJI007/Adblock-Rule-Collection/main/ADBLOCK_RULE_COLLECTION_DOMAIN.txt"
            "https://raw.githubusercontent.com/REIJI007/Adblock-Rule-Collection/main/ADBLOCK_RULE_COLLECTION_HOST.txt"
            "https://raw.githubusercontent.com/REIJI007/Adblock-Rule-Collection/main/ADBLOCK_RULE_COLLECTION_HOST_IPV6.txt"
            "https://raw.githubusercontent.com/dotywrt/block-torrent/refs/heads/main/Thosts"
          )

          COMBINED="combined_hosts.tmp"
          > "$COMBINED"

          for url in "${FILES[@]}"; do
            echo "Downloading $url..."
            curl -s "$url" >> "$COMBINED"
          done

      - name: Clean and format hosts
        run: |
          CLEANED="netguard.txt"

          # Remove 0.0.0.0 prefix and whitespace
          sed -E 's/^\s*0\.0\.0\.0\s+//g' combined_hosts.tmp > hosts_only.tmp

          # Remove empty lines, comments, and invalid domain names
          grep -E '^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$' hosts_only.tmp > hosts_valid.tmp

          # Prepend 0.0.0.0 to each line
          awk '{print "0.0.0.0 "$1}' hosts_valid.tmp > "$CLEANED"

          # Remove duplicates
          sort -u "$CLEANED" -o "$CLEANED"

          # Optional: preview first 10 lines
          head -n 10 "$CLEANED"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "dotywrt"
          git config user.email "dotywrt@gmail.com"
          git add netguard.txt
          git commit -m "Update NetGuard hosts list" || echo "No changes to commit"
          git push
