name: Update Hosts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # daily at 00:00 UTC

jobs:
  combine_hosts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl grep sed coreutils

      - name: Download and combine host files
        run: |
          FILES=(
            "https://raw.githubusercontent.com/REIJI007/Adblock-Rule-Collection/main/ADBLOCK_RULE_COLLECTION_DOMAIN.txt"
            "https://raw.githubusercontent.com/REIJI007/Adblock-Rule-Collection/main/ADBLOCK_RULE_COLLECTION_HOST.txt"
            "https://raw.githubusercontent.com/REIJI007/Adblock-Rule-Collection/main/ADBLOCK_RULE_COLLECTION_HOST_IPV6.txt"
            "https://raw.githubusercontent.com/dotywrt/block-torrent/refs/heads/main/Thosts"
          )

          COMBINED="combined_hosts.txt"
          > "$COMBINED"

          for url in "${FILES[@]}"; do
            echo "Downloading $url..."
            curl -s "$url" >> "$COMBINED"
          done

      - name: Clean combined file
        run: |
          # Remove empty lines and comments
          sed -i '/^\s*$/d' combined_hosts.txt
          sed -i '/^#/d' combined_hosts.txt

          # Remove invalid lines (must contain valid domain format: letters, digits, dots, hyphens)
          grep -E '^[0-9\.]+\s+[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$' combined_hosts.txt > combined_hosts.tmp
          mv combined_hosts.tmp combined_hosts.txt

          # Ensure 0.0.0.0 prefix if not already
          awk '{if($1 != "0.0.0.0") print "0.0.0.0 "$2; else print $0}' combined_hosts.txt > combined_hosts.tmp
          mv combined_hosts.tmp combined_hosts.txt

          # Remove duplicates
          sort -u combined_hosts.txt -o combined_hosts.txt

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add combined_hosts.txt
          git commit -m "Update combined hosts list" || echo "No changes to commit"
          git push
